### ISSUE TITLE
Explosion during teleportation

### ISSUE THREAD

**Issue by 1DAS** [GreyCaat/AeronauticaGUI#1]
Aircraft explodes during teleportation, unknown to why. There's a warning for boats about this, but there isn't one for aircraft. When it explodes is random, sometimes it will and sometimes it won't.

**Comment by GreyCaat** [comment]
closed due to new version and being old

`loadstring(syn.request({Url = "https://raw.githubusercontent.com/GreyCaat/Cat-Hub/main/main.lua"}).Body)()`
